---
- hosts: all
  become: yes  
  vars:
    docker_compose_version: "v2.1.1"
  tasks:
    - name: install docker
      shell: |
          curl https://releases.rancher.com/install-docker/20.10.sh | sh
          pip install docker-compose
          
    - name: Download docker-compose {{ docker_compose_version }}
      get_url:
        url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-aarch64
        dest: ~/docker-compose
        mode: '+x'

    - name: Check docker-compose exists
      stat: path=~/docker-compose
      register: docker_compose

    - name: Move docker-compose to /usr/local/bin/docker-compose
      command: mv ~/docker-compose /usr/local/bin/docker-compose
      when: docker_compose.stat.exists
